{application, lapd,
	[{description,    "Link Access Procedures on the D-channel (LAPD)"},
		{id,           "LAPD"},
		{vsn,          "1.0"},
		{modules,      [lapd_app, lapd_lme_fsm, lapd_cme_fsm,
		                lapd_multiplex_fsm, lapd_fsm]},
		{registered,   []},
		{included_applications, []},
		{applications, [kernel, stdlib]},
		{env,          []}]}.
