
.PHONY: all
all:
	echo "Nothing to be done in doc/html."

.PHONY:	install
install:
	install -d ${ERL_TOP}/lib/lapd-${VERSION}/doc/html
	install -f ${ERL_TOP}/lib/lapd-${VERSION}/doc/html index.html
	install -f ${ERL_TOP}/lib/lapd-${VERSION}/doc/html lapd.html
	install -f ${ERL_TOP}/lib/lapd-${VERSION}/doc/html lapd_mux_fsm.html
	install -f ${ERL_TOP}/lib/lapd-${VERSION}/doc/html supervision_tree.png
	install -f ${ERL_TOP}/lib/lapd-${VERSION}/doc/html process_communication.png

